import "oaidl.idl";
import "ocidl.idl";

[
    local,
    uuid(76320FF8-D666-4BA5-B9EA-19621B435A8D),
    pointer_default(unique)
]
interface ITcpClient : IUnknown
{
    [] HRESULT Write([in] BSTR p_sValue);
};

[
    uuid(9C8D2B38-CBBE-475D-B929-6DE82BCD33F5),
    version(0.1)
]
library IOLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    interface ITcpClient;
};
